import type { PermissionKey, Role, RoleKey } from "@/types";

const ALL: PermissionKey[] = [
  "dashboard.view",
  "learners.view",
  "learners.manage",
  "learners.identity_only",
  "attendance.view",
  "attendance.record",
  "occasions.manage",
  "observations.view",
  "observations.create",
  "cases.view",
  "cases.manage",
  "welfare.view",
  "welfare.manage",
  "health.view",
  "academics.view",
  "academics.manage",
  "reports.view",
  "communication.view",
  "staff.manage",
  "devices.view",
  "devices.manage",
  "audit.view",
  "settings.manage",
];

export const ROLES: Record<RoleKey, Role> = {
  administrator: {
    key: "administrator",
    name: "School Administrator",
    description: "Full access to configuration, staff and all learner records.",
    permissions: ALL,
  },
  headteacher: {
    key: "headteacher",
    name: "Headteacher",
    description: "Oversight of attendance, conduct, welfare and reporting.",
    permissions: ALL.filter((p) => p !== "settings.manage"),
  },
  director_of_studies: {
    key: "director_of_studies",
    name: "Director of Studies",
    description: "Academic oversight, attendance and reporting.",
    permissions: [
      "dashboard.view",
      "learners.view",
      "learners.manage",
      "attendance.view",
      "attendance.record",
      "occasions.manage",
      "observations.view",
      "observations.create",
      "cases.view",
      "academics.view",
      "academics.manage",
      "reports.view",
      "communication.view",
      "devices.view",
    ],
  },
  teacher: {
    key: "teacher",
    name: "Teacher",
    description: "Class attendance, observations and academic entry.",
    permissions: [
      "dashboard.view",
      "learners.view",
      "attendance.view",
      "attendance.record",
      "observations.view",
      "observations.create",
      "academics.view",
      "academics.manage",
      "reports.view",
    ],
  },
  security_officer: {
    key: "security_officer",
    name: "Security Officer",
    description: "Gate scanning, permitted exits and assigned device only.",
    permissions: [
      "dashboard.view",
      "learners.identity_only",
      "attendance.view",
      "attendance.record",
      "occasions.manage",
      "devices.view",
    ],
  },
  nurse: {
    key: "nurse",
    name: "School Nurse",
    description: "Sick bay attendance and health encounters.",
    permissions: [
      "dashboard.view",
      "learners.identity_only",
      "attendance.view",
      "attendance.record",
      "welfare.view",
      "welfare.manage",
      "health.view",
      "observations.create",
      "reports.view",
    ],
  },
  warden: {
    key: "warden",
    name: "Boarding Warden",
    description: "Dormitory roll call, prep and welfare observations.",
    permissions: [
      "dashboard.view",
      "learners.view",
      "attendance.view",
      "attendance.record",
      "occasions.manage",
      "observations.view",
      "observations.create",
      "welfare.view",
      "devices.view",
      "reports.view",
    ],
  },
  transport_officer: {
    key: "transport_officer",
    name: "Transport Officer",
    description: "Bus manifests, transport occasions and assigned devices.",
    permissions: [
      "dashboard.view",
      "learners.identity_only",
      "attendance.view",
      "attendance.record",
      "occasions.manage",
      "devices.view",
      "reports.view",
    ],
  },
};

export const DEMO_ACCOUNTS: { role: RoleKey; name: string; email: string }[] = [
  { role: "administrator", name: "Grace Nakabugo", email: "admin@nilecrest.ac.ug" },
  { role: "headteacher", name: "Samuel Wamala", email: "head@nilecrest.ac.ug" },
  { role: "director_of_studies", name: "Esther Akello", email: "dos@nilecrest.ac.ug" },
  { role: "teacher", name: "Brian Ssemanda", email: "b.ssemanda@nilecrest.ac.ug" },
  { role: "security_officer", name: "Moses Ochieng", email: "gate@nilecrest.ac.ug" },
  { role: "nurse", name: "Faith Atim", email: "sickbay@nilecrest.ac.ug" },
  { role: "warden", name: "Lydia Nabirye", email: "warden@nilecrest.ac.ug" },
  { role: "transport_officer", name: "Daniel Okello", email: "transport@nilecrest.ac.ug" },
];
