FROM node:22-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev=false

FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=dependencies /app/node_modules ./node_modules
COPY package.json ./
COPY prisma ./prisma
COPY server ./server
RUN ./node_modules/.bin/prisma generate
USER node
EXPOSE 3001
CMD ["./node_modules/.bin/tsx", "server/index.ts"]
