/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ObservationsRouteImport } from './routes/observations'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LearnersIndexRouteImport } from './routes/learners.index'
import { Route as LearnersIdRouteImport } from './routes/learners.$id'
import { Route as LearnersNewRouteImport } from './routes/learners.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsRoute = ObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersIndexRoute = LearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersIdRoute = LearnersIdRouteImport.update({
  id: '/learners/$id',
  path: '/learners/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersNewRoute = LearnersNewRouteImport.update({
  id: '/learners/new',
  path: '/learners/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cases': typeof CasesRoute
  '/observations': typeof ObservationsRoute
  '/occasions': typeof OccasionsRoute
  '/scan': typeof ScanRoute
  '/staff': typeof StaffRoute
  '/learners/$id': typeof LearnersIdRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cases': typeof CasesRoute
  '/observations': typeof ObservationsRoute
  '/occasions': typeof OccasionsRoute
  '/scan': typeof ScanRoute
  '/staff': typeof StaffRoute
  '/learners/$id': typeof LearnersIdRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners': typeof LearnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cases': typeof CasesRoute
  '/observations': typeof ObservationsRoute
  '/occasions': typeof OccasionsRoute
  '/scan': typeof ScanRoute
  '/staff': typeof StaffRoute
  '/learners/$id': typeof LearnersIdRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/cases'
    | '/observations'
    | '/occasions'
    | '/scan'
    | '/staff'
    | '/learners/$id'
    | '/learners/new'
    | '/learners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/cases'
    | '/observations'
    | '/occasions'
    | '/scan'
    | '/staff'
    | '/learners/$id'
    | '/learners/new'
    | '/learners'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/cases'
    | '/observations'
    | '/occasions'
    | '/scan'
    | '/staff'
    | '/learners/$id'
    | '/learners/new'
    | '/learners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CasesRoute: typeof CasesRoute
  ObservationsRoute: typeof ObservationsRoute
  OccasionsRoute: typeof OccasionsRoute
  ScanRoute: typeof ScanRoute
  StaffRoute: typeof StaffRoute
  LearnersIdRoute: typeof LearnersIdRoute
  LearnersNewRoute: typeof LearnersNewRoute
  LearnersIndexRoute: typeof LearnersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/': {
      id: '/learners/'
      path: '/learners'
      fullPath: '/learners/'
      preLoaderRoute: typeof LearnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/$id': {
      id: '/learners/$id'
      path: '/learners/$id'
      fullPath: '/learners/$id'
      preLoaderRoute: typeof LearnersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/new': {
      id: '/learners/new'
      path: '/learners/new'
      fullPath: '/learners/new'
      preLoaderRoute: typeof LearnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CasesRoute: CasesRoute,
  ObservationsRoute: ObservationsRoute,
  OccasionsRoute: OccasionsRoute,
  ScanRoute: ScanRoute,
  StaffRoute: StaffRoute,
  LearnersIdRoute: LearnersIdRoute,
  LearnersNewRoute: LearnersNewRoute,
  LearnersIndexRoute: LearnersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
