/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnersIndexRouteImport } from './routes/learners.index'
import { Route as LearnersNewRouteImport } from './routes/learners.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersIndexRoute = LearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersNewRoute = LearnersNewRouteImport.update({
  id: '/learners/new',
  path: '/learners/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners': typeof LearnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learners/new': typeof LearnersNewRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learners/new' | '/learners/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learners/new' | '/learners'
  id: '__root__' | '/' | '/learners/new' | '/learners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnersNewRoute: typeof LearnersNewRoute
  LearnersIndexRoute: typeof LearnersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/': {
      id: '/learners/'
      path: '/learners'
      fullPath: '/learners/'
      preLoaderRoute: typeof LearnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/new': {
      id: '/learners/new'
      path: '/learners/new'
      fullPath: '/learners/new'
      preLoaderRoute: typeof LearnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnersNewRoute: LearnersNewRoute,
  LearnersIndexRoute: LearnersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
